### ISSUE TITLE
SAWarning: Can't resolve label reference 'count_1 desc'; converting to text() 

### ISSUE THREAD

**Issue by papachoco** [fedora-infra/tahrir-api#36]
SQLAlchemy 1.0.0 just got release. I observed the warning 

SAWarning: Can't resolve label reference 'count_1 desc'; converting to text()

is thrown at dbapi.TahrirDatabase._make_leaderboard

It seems it does not cause any harm. but I wanted to make you aware

Carlos

**Comment by AdamWill** [comment]
A mere four years later, this breaks the world:

    CompileError: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'count_1 desc' should be explicitly declared as text('count_1 desc')

seems to be with SQLAlchemy 1.3+ this is finally an error not a warning. I'll send a PR...
